name: base-server auto build
run-name: ${{ gitea.actor }} is testing out Gitea Actions  
on: 
  push:
    branches: 
      - main
jobs:
  Explore-Gitea-Actions:
    runs-on: debian
    # 发版时才会部署，正常提交不部署
    if: "contains(gitea.event.head_commit.message, 'chore(release)')"
    steps:
      - run: echo "  The job was automatically triggered by a ${{ gitea.event_name }} event."
      - run: echo "  This job is now running on a ${{ runner.os }} server hosted by Gitea!"
      - run: echo "  The name of your branch is ${{ gitea.ref }} and your repository is ${{ gitea.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: 下载依赖
        run: |
          npm i -g pnpm
          pnpm install
      - name: 构建项目
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: pnpm build
      - name: 复制到目标目录
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          rm -rf /root/server/zzclub-base-server/*
          mkdir -p /root/server/zzclub-base-server/prisma
          cp -R .output/* /root/server/zzclub-base-server/
          cp -R prisma/* /root/server/zzclub-base-server/prisma/
          cp -R pm2.config.yml /root/server/zzclub-base-server/pm2.config.yml
      # pm2 重启时使用 pm2 restart pm2.config.yml
      - name: 启动项目
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          cd /root/server/zzclub-base-server
          npx prisma generate
          prisma migrate deploy
          pm2 start pm2.config.yml
      - run: echo "  The ${{ gitea.repository }} repository has been cloned to the runner."
      - run: echo " ️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ gitea.workspace }}          
      - run: echo "  This job's status is ${{ job.status }}."
      # 飞书消息通知
      - name: Send FeiShu Notification
        if: always()
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{
              "msg_type": "text",
              "content": {
                "text": "${{ gitea.repository }} - release [${{job.status}}]"
              }
            }' \
            "${{ secrets.FEISHU_WEBHOOK }}"